### ISSUE TITLE
Citation for SOG Lasso

### ISSUE THREAD

**Issue by richford** [richford/afq-insight-paper#10]
[This line](https://github.com/richford/afq-insight-paper/blob/71cb8e133bd45a0b89fcce820dfc24e2b595b4ba/reports/manuscript/sections/conclusion.tex#L72) requests a citation for SGL with overlapping groups. There are a few options here but I think [this paper](http://nowak.ece.wisc.edu/sog_lasso.pdf) might be the best fit. Your thoughts @arokem and @nrs02004 .

**Comment by arokem** [comment]
I think this was addressed in https://github.com/richford/afq-insight-paper/commit/6e6ef70b7d7a1ac493fded215c615a3b53309aaf. Closing.
