### ISSUE TITLE
Fix requirements.txt and installation issues

### ISSUE THREAD

**Issue by richford** [richford/afq-insight-paper#4]
Ariel had to install the following packages by hand:
- All copy dependencies
- palatable
- bokeh
- dipy
- hyperopt
- fury

**Comment by arokem** [comment]
Also: requests (to run ‘make data’)

**Comment by richford** [comment]
Resolved with commits [48f0c8e](https://github.com/richford/afq-insight-paper/commit/48f0c8e69ed96e4c417a8f5aa42144aed582d96b) through [6889fc6](https://github.com/richford/afq-insight-paper/commit/6889fc68b89ea35c1d905f9e25a197f3d363bf51).
